# Generated by Django 5.0.1 on 2024-01-16 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverer',
            name='works_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='franchise.franchise'),
        ),
    ]
